apiVersion: batch/v1
kind: Job
metadata:
  name: banking-schema
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  backoffLimit: 8
  activeDeadlineSeconds: 600
  template:
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: schema
          image: '{{ .Values.backend.repository }}:{{ .Values.backend.tag }}'
          command: [python, -m, app.db]
          envFrom:
            - secretRef: {name: {{ .Values.secretName }}}
